using System; // IMPORTAREMOS TODO LO NECESARIO PARA ESTE PROYECTO EN PARTICULAR.
using System.Collections.Generic; // IMPORTAREMOS TODO LO NECESARIO PARA ESTE PROYECTO EN PARTICULAR.
using System.ComponentModel; // IMPORTAREMOS TODO LO NECESARIO PARA ESTE PROYECTO EN PARTICULAR.
using System.Data; // IMPORTAREMOS TODO LO NECESARIO PARA ESTE PROYECTO EN PARTICULAR.
using System.Drawing; // IMPORTAREMOS TODO LO NECESARIO PARA ESTE PROYECTO EN PARTICULAR.
using System.Linq; // IMPORTAREMOS TODO LO NECESARIO PARA ESTE PROYECTO EN PARTICULAR.
using System.Text; // IMPORTAREMOS TODO LO NECESARIO PARA ESTE PROYECTO EN PARTICULAR.
using System.Threading.Tasks; // IMPORTAREMOS TODO LO NECESARIO PARA ESTE PROYECTO EN PARTICULAR.
using System.Windows.Forms; // IMPORTAREMOS TODO LO NECESARIO PARA ESTE PROYECTO EN PARTICULAR.

namespace Pokemon
{
    public partial class Form1 : Form
    {
        // AQUÍ VAMOS A DECLARAR ALGUNAS VARIABLES AL PROYECTO...

        int turn = 1; // VARIABLE PARA TURNARSE 2 JUGADORES ENTRE SÍ.
        int[,] TicTacToe; // VARIABLE MEDIANTE UNA MATRIZ CUADRADA DE 3 * 3.
        int PlayerPoints = 1; // COMIENZA UNA PARTIDA CON 0 PUNTOS PARA EL JUGADOR.
        int PlayerPoints2 = 0; // COMIENZA UNA PARTIDA CON 0 PUNTOS PARA EL RIVAL.
        bool YouHaveAWinner; // VARIABLE BOOLEANA QUE DEFINE UN GANADOR PARA AMBOS JUGADORES CUALQUIERA DEPENDIENDO DEL DESEMPEÑO QUE OBTUVIERON EN UNA PARTIDA.

        public Form1()
        {
            InitializeComponent();
        }
    }
}